### ISSUE TITLE
Update 8.2 Don't Work On Figma

### ISSUE THREAD

**Issue by rotemgrid** [google/AEUX#152]
Updated (0.8.2) AEUX on Figma but UI shows it still on the old version 
see screenshot attached
And now it won't cast to after because it uses the new version

Tried to downgrade the version to both Figma and after but it doesn't work

<img width="184" alt="Screen Shot 2022-11-14 at 15 47 03" src="https://user-images.githubusercontent.com/11423749/201676057-713831bb-c4fa-4efc-a6e9-2218f2e1937d.png">

**Comment by juanmr8** [comment]
@rotemgrid how did you manage to solve it? I am experiencing the same.
