### ISSUE TITLE
Always in the "send selection to ae" state.

### ISSUE THREAD

**Issue by K0HEX** [google/AEUX#191]
**Describe the bug**
When I designed the elements in figma and clicked send selection to ae, the figma plug-in was always in the send selection to ae state, and the import and synthesis of materials was not completed in ae, but my picture resources were exported in the local folder.
@vmedium 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [macOS 14.1]
 - Version [figma 116.13.3]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JANCHOU0829** [comment]
> **Describe the bug** When I designed the elements in figma and clicked send selection to ae, the figma plug-in was always in the send selection to ae state, and the import and synthesis of materials was not completed in ae, but my picture resources were exported in the local folder. @vmedium **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [macOS 14.1]
> * Browser [e.g. chrome, safari]
> * Version [figma 116.13.3]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> **Additional context** Add any other context about the problem here.

I tried it on another computer and it worked fine.

AE: 2021 18.2.1 build 8

macOS: 13.1

Figma: 116.7.103

So I assume it may be due to the version of macOS. I recently upgraded my macOS to the latest version, so please check if the plugin is not compatible with macOS version 14.1

**Comment by kjacovino** [comment]
Same issue—saves images to the folder, but doesn't load anything in AE.

* MacOS: 14.0
* AE: 24.0.0 (Build 55)
* Figma: 116.13.3

**Comment by vmedium** [comment]
All I can recommend is update all the things.

Then try one thing at a time.

Make a figma file, make a frame, make a circle in the frame, use AEUX to
import this.

Then try an image. The. Try some type. Etc.

Usually that’s how I break down finding out what is breaking.

**Comment by kjacovino** [comment]
Appreciate that and gave it a shot, but everything is up to date (Figma, MacOS, AE), and nothing at all will import. I've also restarted everything multiple times, including the computer, but no dice.

**Comment by K0HEX** [comment]
> **Describe the bug** When I designed the elements in figma and clicked send selection to ae, the figma plug-in was always in the send selection to ae state, and the import and synthesis of materials was not completed in ae, but my picture resources were exported in the local folder. @vmedium **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [macOS 14.1]
> * Browser [e.g. chrome, safari]
> * Version [figma 116.13.3]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone6]
> * OS: [e.g. iOS8.1]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]
> 
> **Additional context** Add any other context about the problem here.



> **Describe the bug 描述错误** When I designed the elements in figma and clicked send selection to ae, the figma plug-in was always in the send selection to ae state, and the import and synthesis of materials was not completed in ae, but my picture resources were exported in the local folder.  @vmedium **To Reproduce 复制** Steps to reproduce the behavior:重现行为的步骤：
> 
> 1. Go to '...' 去'...'
> 2. Click on '....' 点击“....”
> 3. Scroll down to '....'向下滚动到'....'
> 4. See error 查看错误
> 
> **Expected behavior 预期行为** A clear and concise description of what you expected to happen.对您所期望发生的事情进行明确而简洁的描述。
> 
> **Screenshots 截图** If applicable, add screenshots to help explain your problem.如适用，请添加屏幕截图以帮助解释您的问题。
> 
> **Desktop (please complete the following information):桌面（请填写以下信息）：**
> 
> * OS: [macOS 14.1] 操作系统：[macOS 14.1]
> * Browser [e.g. chrome, safari]浏览器 [例如 chrome，safari]
> * Version [figma 116.13.3]版本 [figma 116.13.3]
> 
> **Smartphone (please complete the following information):智能手机（请填写以下信息）：**
> 
> * Device: [e.g. iPhone6] 设备：[例如 iPhone6]
> * OS: [e.g. iOS8.1] 操作系统：[例如 iOS8.1]
> * Browser [e.g. stock browser, safari]浏览器 [例如原生浏览器，Safari]
> * Version [e.g. 22] 版本 [例如 22]
> 
> **Additional context 附加背景** Add any other context about the problem here.在这里添加有关问题的任何其他背景。
I solved this problem by upgrading the AE version. My current AE version is 23.6.0 build 62, and the previous version before the upgrade was 22.6.0 (Build 64).
