### ISSUE TITLE
Did something just happen to AEUX?

### ISSUE THREAD

**Issue by ZapRowsdowerr** [google/AEUX#203]
I was using AEUX in a Figma to After Effects workflow last week and everything was working fine. 
Yesterday, I got the "Failed to connect to AE" error message when trying to send my selection to AE. 
I thought maybe I'd remove, re-download, and re-install AEUX and see if that fixed the problem. However, when I go to https://aeux.io/, I get an error saying the site cannot be reached. https://aeux.io/guide/install.html also cannot be reached. It seems that all AEUX sites are unreachable. 

Does anyone know if something happened recently with AEUX?

![Screenshot 2024-03-01 083944](https://github.com/google/AEUX/assets/161866365/07345f2e-8366-4e62-85a6-3bb7633c58ce)

![Screenshot 2024-03-01 084028](https://github.com/google/AEUX/assets/161866365/17f96852-0dab-480e-a6a5-bd5e5046af64)

**Comment by vmedium** [comment]
https://github.com/google/AEUX/releases

Here's a path to the downloadable zip. The aeux.io website disappeared because no one is maintaining it at google.

**Comment by adamplouff** [comment]
New docs site at:

https://google.github.io/AEUX/

**Comment by ZapRowsdowerr** [comment]
Thank you for your help. I was able to do a fresh install. 
Apparently the zxp for After Effects didn't survive when I updated to a new AE version, but once I re-did the process with the zxp the problem was gone.
